### ISSUE TITLE
Mod Request: "I'm Walking Here" @ https://www.nexusmods.com/skyrimspecialedition/mods/27742

### ISSUE THREAD

**Issue by draconicfragor** [EzioTheDeadPoet/Tales-from-the-Northern-Lands#24]
https://www.nexusmods.com/skyrimspecialedition/mods/27742

Makes it possible to walk through allies (summoned Minions, Followers) and optionally disables their collision comments, making for far less annoying allies. Quickly became a must for me, and is thankfully quite easy to add on to a pack.

**Comment by EzioTheDeadPoet** [comment]
The next update will feature this. It does effectively the same. 👌 
https://www.nexusmods.com/skyrimspecialedition/mods/35925
