### ISSUE TITLE
A few mods to think about adding

### ISSUE THREAD

**Issue by wubbs37** [EzioTheDeadPoet/Tales-from-the-Northern-Lands#25]
**Request**
A clear and concise description of what your feature requested is. This can be anything from README changes to adding new mods.
 I've Tested the following and only ran into one minor issue so far, pretty sure relatively easily patchable by someone with the knowhow. About a dozen or so hours into playthrough. Just slapped them on and loaded them last.

https://www.nexusmods.com/skyrimspecialedition/mods/12708 - Achieve That SE - adds a fairly balanced "badass token" like system for mod-added achievements, encourages multiple playthroughs as many are mutually exclusive

https://www.nexusmods.com/skyrimspecialedition/mods/23329 - Attribute Value Application - Adds attributes to the game, which can be raised (in theory) by raising appropriate skills. Allows for a class-like experience while still allowing for players to branch out into anything, although potentially nerfed due to buffs spent elsewhere, or can be made "completely average" with no buffs or debuffs. Optional Maybe? Ran into a minor problem with this one, but it doesn't break anything really. Only some skills seem to raise attributes when they should (lvl 50 and 100), but afaik the mod isn't tied to perks so I'm not sure what the issue is. I've used it with Ordinator in the past, no patch, no problem. 

https://www.nexusmods.com/skyrimspecialedition/mods/39386 - Unobtrusive Candlelight Fix - Moves the candlelight behind you so it doesn't blind you for having the audacity for trying to use a shield underground. 

https://www.nexusmods.com/skyrimspecialedition/mods/9383 - Casting Regeneration - Once your possibly very mana-expensive spell is charged, you can wait for your mana to recharge before casting, giving you a full mana pool AND one or two spells at the start of each fight that you start.

**Additional context**

**Comment by EzioTheDeadPoet** [comment]
I finally looked at the mods, so far they aren't really hitting my personal taste/vision. 
At least not now.
I will leave this open tho so I have a reference, if I feel like "something is missing".
