### ISSUE TITLE
Wampire lord Crash. 

### ISSUE THREAD

**Issue by TomasHusivarga** [EzioTheDeadPoet/Tales-from-the-Northern-Lands#32]
**Describe the bug**
I accepted to become vampire after bringig Serana back to the castle (Start of the Dawnguard) after transition to tutorial area I activate change to Vampire Lord and game crashes. I tried to restart game and pc few times but it always crashes right as change happenes. Right when model changes from human to VampLord.

**To Reproduce**
Accept to become Vamprie from Volkihar, then in tutorial are try to use Vampire Lord power. It always crashes for me. 

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, take a screenshot of `You are Here` MCM Option from DynDOLOD as well as a screenshot of the world map.

**Modlist version**
Do not say latest
2.1.1 (Balanced)(No adational modifications) (Installed from wabbajack and played)

**Did you add any additional mods?**
No

**Comment by TomasHusivarga** [comment]
Problem is with " Scion - A Vampire Overhaul " when i disable that mod game no longer crashes during Vampire Lord transformation.

**Comment by EzioTheDeadPoet** [comment]
Can you please upload the crash-log files. 

They are found in `Screenshots ! Racemenu Presets ! Game Generated`

and in there in the `NetScriptFramework/Crash` folder.

Cause finding the actual issue is important to me.

**Comment by Tomas1564230** [comment]
[Crash_2021_12_27_22-9-1.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855691/Crash_2021_12_27_22-9-1.txt)

**Comment by TomasHusivarga** [comment]
[Crash_2022_1_12_16-15-3.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855693/Crash_2022_1_12_16-15-3.txt)

This is latest report.

**Comment by TomasHusivarga** [comment]
[Crash_2022_1_12_15-46-34.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855703/Crash_2022_1_12_15-46-34.txt)
[Crash_2022_1_12_16-15-3.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855704/Crash_2022_1_12_16-15-3.txt)
[Crash_2022_1_12_15-55-50.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855705/Crash_2022_1_12_15-55-50.txt)
[Crash_2022_1_12_15-54-8.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855706/Crash_2022_1_12_15-54-8.txt)
[Crash_2022_1_12_15-52-1.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855707/Crash_2022_1_12_15-52-1.txt)
[Crash_2022_1_12_15-50-17.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855708/Crash_2022_1_12_15-50-17.txt)
[Crash_2022_1_12_15-48-37.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855709/Crash_2022_1_12_15-48-37.txt)

**Comment by EzioTheDeadPoet** [comment]
[loadorder.txt.zip](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855730/loadorder.txt.zip)

could you put the 3 files in that zip into the `ModOrganizer 2\profiles\Tales from the Northern Lands (Balanced)` Folder and then hit this button:
![image](https://user-images.githubusercontent.com/52624146/149171102-49e7dd48-8c03-4412-9584-bff583261f2b.png)
on the plugins tab (right side)
![image](https://user-images.githubusercontent.com/52624146/149171225-8782c234-407e-4335-83d2-c9a0ad51e34b.png)


I am pretty sure I messed up a mod order there. That backup should reorder it.

**Comment by TomasHusivarga** [comment]
There are no backup to restore.

**Comment by TomasHusivarga** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/97563524/149172949-1d62f0a8-93a3-4e30-90f8-010dac1b0ad7.png)

**Comment by EzioTheDeadPoet** [comment]
how does the folder look did you extract the zip

**Comment by TomasHusivarga** [comment]
First like that, but then i deleted numbers after .txt and replaced ones that were in Tales from the Northern Lands (Balanced)
![image](https://user-images.githubusercontent.com/97563524/149173336-a21e45d9-c37b-4846-9738-7696c334c04e.png)

**Comment by EzioTheDeadPoet** [comment]
that screenshot is inside the archive and not extracted
drop them like they are here in the folder where the originals ones are and hit the restore button then launch the game an see if the transformation works

**Comment by EzioTheDeadPoet** [comment]
your rename might work as well but it might not work if modorganizer 2 is open while replacing the file.

**Comment by TomasHusivarga** [comment]
![image](https://user-images.githubusercontent.com/97563524/149173803-ed3f0b99-0037-42f4-8dd7-b6c1e54714e1.png)

This is folder after i click rewrite the files during transfer.

**Comment by TomasHusivarga** [comment]
FNIS missing and still crashes. 

Backup worked second time i unzipped files.

**Comment by TomasHusivarga** [comment]
[Crash_2022_1_12_16-52-55.txt](https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/files/7855922/Crash_2022_1_12_16-52-55.txt)

**Comment by EzioTheDeadPoet** [comment]
FNIS missing is on purpose

![image](https://user-images.githubusercontent.com/52624146/149174699-a88f4815-111c-4a4d-9bcd-9b1c73a3e405.png)
my guess scion and this mod have an incompatibility causing the crash. can you try to redo the transformation with that mod disabled but scion enabled. and send the log of that.

**Comment by TomasHusivarga** [comment]
Ok, so old save is in infinite loading. But new game runs and I tried add VampLord power and it didn't crash during transformation. 

Where do I find log if it is not a crash?

**Comment by EzioTheDeadPoet** [comment]
Sadly there is no way for a log with that info. Guess I will have to remove the mon in an update that will require a new save soon.

**Comment by TomasHusivarga** [comment]
Sorry :) 

But new save works fine, thank you so much for help!

**Comment by EzioTheDeadPoet** [comment]
thx for reporting it and trying the stuff for me 👍
