### ISSUE TITLE
T-Pose Bug when walking sideways.

### ISSUE THREAD

**Issue by antun0** [EzioTheDeadPoet/Tales-from-the-Northern-Lands#5]
Character goes into a t-pose when you walk sideways in both first and third person. Won't stop until you stop moving and let the idle activate.

**Comment by EzioTheDeadPoet** [comment]
how much fps do you get while playing ? 
is it above 75 or something around that number ?
If I remember correctly one of the mods used that gives your character procedural leaning stops working somewhere around that number.

And thanks for reporting it. 

I will look if I can find a fix for it to be able to play at a higher frame rate, but until then I will probably make an update to the list that locks the frame rate at 60FPS.

**Comment by antun0** [comment]
Yeah I am playing att over 75 fps. Thanks for pointing it out! I'll just lock my framrate for the time being.

**Comment by EzioTheDeadPoet** [comment]
tell me if it worked if it did I will close this issue.

**Comment by antun0** [comment]
Yeah that fixed it!
