### ISSUE TITLE
Experience and/or Timing is Everything+Not So Fast

### ISSUE THREAD

**Issue by SovnSkyrim** [EzioTheDeadPoet/Tales-from-the-Northern-Lands#9]
**Request**
Experience: Slowers leveling by making it so quests level you up instead of your skills level.
Not So Fast Main Quest, I think it's mandatory in any 

**Additional context**
Still think you level a bit too fast, Not so fast Main Quest is just because it makes sense

**Comment by EzioTheDeadPoet** [comment]
Pretty solid ideas I totally missed even though I know them. 🤦‍♂️
They will most likely make it into the next update.
